---
- name: "Configuration de base du poste local"
  hosts: localhost
  gather_facts: true
  become: yes
  become_method: sudo
  roles:
    - role: "gecos_root"
    - role: "outils-base"
    - role: "zsh"
    - role: "vimrc"
    - role: "selinux"
      vars:
        enableselinux: no
      when: ansible_distribution_file_variety == "RedHat"
    - role: "disable-swap"
      when: ansible_distribution_file_variety == "RedHat"
    - role: "epel"
      when: ansible_distribution_file_variety == "RedHat"
